### PR TITLE
fix missing zip package in dockerfile

### PR DESCRIPTION
**Pull request by eliottthomas1**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Fix for missing Zip package in Dockerfile.
Docker image successfully builds with this package included.

### References

https://github.com/auth0/repo-supervisor/issues/41

### Testing

Build the docker image with the version 3.0.0 changes and include the Zip package as i have done.

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by radekk** [comment]
@eliottthomas1 one more thing, would it be possible to GPG sign this commit? otherwise I can't merge it since we blocked merging non-signed commits and it's enforced on the repository level. You can rebase your branch to sign already commited changes and push force that.

**References:**
- https://superuser.com/questions/397149/can-you-gpg-sign-old-commits
- https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by eliottthomas1** [comment]
@radekk yep sure will sign and recommit

**Comment by radekk** [comment]
Perfect! Thanks, it looks good now. Let me merge that.

**Comment by radekk** [comment]
I just fixed the latest commit in the master branch. I merged this PR using squash method and it didn't authored this commit with your details which I didn't like. I don't want to get credits for your work. It seems to be an issue how github handles that: https://github.com/isaacs/github/issues/1368#issuecomment-595111126

It should be good right now and you're listed as a contributor 👍

**Pull request merged**
