### PR TITLE
Find secrets in any file, not just *.js and *.json

### PR DESCRIPTION
**Pull request by JasonTarka**
This will take any regular file and split out strings based on a list of common separators

### CODE REVIEW

**Comment by shawkinsl** [comment]
This PR is awesome! Using these changes, I can find secrets in html, python, etc. Thanks!

**Comment by ramya-ravula-ctr** [comment]
it's working for ./dist/cli.js but when i try to scan .txt or .py files using webhooks and wt url, unable to detect secrets or match pattern

**Comment by radekk** [comment]
I really like this PR but it somehow breaks the main idea for the repo supervisor. It was expected to return as low false-positives as possible. Scanning all types of files will introduce a lot of noise.

It could be helpful for scanning text files but for or other formats like python, html etc. it should have tokenizers in place for those languages.

I need to think through that and probably we might introduce this idea as the `.txt` extension parser. I will put that in our roadmap with a link to this PR to keep a contribution note to your user.

Thanks Jason!

**Comment by radekk** [comment]
@JasonTarka would you be able to extract changes from the file you modified in this PR `src/filters/index.js` ? It add a useful syntax check I would like to put into the code.

**Pull request closed without merging**
